#!groovy

properties([
    disableConcurrentBuilds(),
    buildDiscarder(logRotator(artifactDaysToKeepStr: '',
                              artifactNumToKeepStr: '',
                              daysToKeepStr: '',
                              numToKeepStr: '100')),
    parameters([string(name: 'SLACK_CHANNEL', defaultValue: '#shinyloadtest', description: 'Slack channel to publish build message.')])
])

def prepareWorkspace(){
  step([$class: 'WsCleanup'])
  checkout scm
  sh 'git reset --hard && git clean -ffdx'
}

try {
  timestamps {
    node('docker') {
      stage('prepare ws/container') {
        prepareWorkspace()
        container = pullBuildPush(image_name: 'jenkins/proxyrec-player', dockerfile: 'player/Dockerfile', image_tag: 'ubuntu-16.04-x86_64', build_arg_jenkins_uid: 'JENKINS_UID', build_arg_jenkins_gid: 'JENKINS_GID')
      }
      container.inside() {
        stage('mvn package') {
          sh """
          cd player
          mvn package
          """
        }
      }
      stage('s3 upload') {
        // TODO
        // s3_upload(current_container.os, current_container.arch)
      }
    }
    sendNotifications slack_channel: params.SLACK_CHANNEL
  }
} catch (err) {
   sendNotifications slack_channel: params.SLACK_CHANNEL, result: 'FAILURE'
   error("proxyrec player build failed: ${err}")
}
